/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>
#include "stm32wbxx_hal.h"
#include "stm32wbxx_ll_bus.h"
#include "stm32wbxx_ll_gpio.h"

#include "FreeRTOS.h"
#include "task.h"

#include "rcc.h"

#warning "Preprocessor include paths and MACROS (symbols) are different for debug and release configuration."

void first_task(void *param);
void second_task(void *param);

int main(void)
{
	NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);

	rcc_init();

	// first task
	xTaskCreate(first_task, "first", 256, NULL, 2, NULL);

	// second task
	xTaskCreate(second_task, "second", 256, NULL, 1, NULL);

	vTaskStartScheduler();
}

void first_task(void *param) {

	LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOE);

	LL_GPIO_InitTypeDef on_board_led_config;
	LL_GPIO_StructInit(&on_board_led_config);

	on_board_led_config.Pin = LL_GPIO_PIN_4;
	on_board_led_config.Mode = LL_GPIO_MODE_OUTPUT;
	on_board_led_config.Speed = LL_GPIO_SPEED_FREQ_HIGH;
	on_board_led_config.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
	on_board_led_config.Pull = LL_GPIO_PULL_NO;

	LL_GPIO_Init(GPIOE, &on_board_led_config);

	for (;;) {

		LL_GPIO_TogglePin(GPIOE, LL_GPIO_PIN_4);

		vTaskDelay(pdMS_TO_TICKS(500));

	}
}

void second_task(void *param) {

	LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOB);

	LL_GPIO_InitTypeDef on_board_led_config;
	LL_GPIO_StructInit(&on_board_led_config);

	on_board_led_config.Pin = LL_GPIO_PIN_2;
	on_board_led_config.Mode = LL_GPIO_MODE_OUTPUT;
	on_board_led_config.Speed = LL_GPIO_SPEED_FREQ_HIGH;
	on_board_led_config.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
	on_board_led_config.Pull = LL_GPIO_PULL_NO;

	LL_GPIO_Init(GPIOB, &on_board_led_config);

	for (;;) {

		LL_GPIO_TogglePin(GPIOB, LL_GPIO_PIN_2);

		vTaskDelay(pdMS_TO_TICKS(2000));
	}
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {

	for (;;);
	;
}
